[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "google-cloud-texttospeech>=2.27.0",
    "moviepy>=2.2.1",
    "openai>=1.101.0",
    "pydub>=0.25.1",
    "pytube>=15.0.0",
    "streamlit>=1.48.1",
    "yt-dlp>=2025.8.20",
]
